// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoRental.Data;

namespace VideoRental.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220609132914_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoRental.Models.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            ActorName = "Johnny Depp",
                            Gender = "Male"
                        },
                        new
                        {
                            ActorId = 2,
                            ActorName = "Tom Hanks",
                            Gender = "Male"
                        },
                        new
                        {
                            ActorId = 3,
                            ActorName = "Emma Watson",
                            Gender = "Female"
                        },
                        new
                        {
                            ActorId = 4,
                            ActorName = "Angelina Jolie",
                            Gender = "Female"
                        },
                        new
                        {
                            ActorId = 5,
                            ActorName = "Daniel Radcliffe",
                            Gender = "Male"
                        },
                        new
                        {
                            ActorId = 6,
                            ActorName = "Meryl Streep",
                            Gender = "Female"
                        },
                        new
                        {
                            ActorId = 7,
                            ActorName = "Will Smith",
                            Gender = "Male"
                        },
                        new
                        {
                            ActorId = 8,
                            ActorName = "Natalie Portman",
                            Gender = "Female"
                        },
                        new
                        {
                            ActorId = 9,
                            ActorName = "Kate Winslet",
                            Gender = "Female"
                        },
                        new
                        {
                            ActorId = 10,
                            ActorName = "Helena Bonham Carter",
                            Gender = "Female"
                        },
                        new
                        {
                            ActorId = 11,
                            ActorName = "Robert Downey Jr",
                            Gender = "Male"
                        },
                        new
                        {
                            ActorId = 12,
                            ActorName = "Leonardo DiCaprio",
                            Gender = "Male"
                        },
                        new
                        {
                            ActorId = 13,
                            ActorName = "Brad Pitt",
                            Gender = "Male"
                        },
                        new
                        {
                            ActorId = 14,
                            ActorName = "Morgan Freemen",
                            Gender = "Male"
                        },
                        new
                        {
                            ActorId = 15,
                            ActorName = "Tommy Lee Jones",
                            Gender = "Male"
                        },
                        new
                        {
                            ActorId = 16,
                            ActorName = "Alan Rickman",
                            Gender = "Male"
                        });
                });

            modelBuilder.Entity("VideoRental.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "USA"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "Italy"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryName = "France"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryName = "UK"
                        },
                        new
                        {
                            CountryId = 5,
                            CountryName = "Canada"
                        });
                });

            modelBuilder.Entity("VideoRental.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Age = 34,
                            CustomerName = "Elise Bryan"
                        },
                        new
                        {
                            CustomerId = 2,
                            Age = 43,
                            CustomerName = "Hayden Rowley"
                        },
                        new
                        {
                            CustomerId = 3,
                            Age = 31,
                            CustomerName = "Emma Morrison"
                        },
                        new
                        {
                            CustomerId = 4,
                            Age = 28,
                            CustomerName = "Archie Hammond"
                        },
                        new
                        {
                            CustomerId = 5,
                            Age = 52,
                            CustomerName = "Robert Davison"
                        },
                        new
                        {
                            CustomerId = 6,
                            Age = 14,
                            CustomerName = "Charles McLean"
                        },
                        new
                        {
                            CustomerId = 7,
                            Age = 10,
                            CustomerName = "Melissa Wilkinson"
                        },
                        new
                        {
                            CustomerId = 8,
                            Age = 36,
                            CustomerName = "Rebecca Middleton"
                        });
                });

            modelBuilder.Entity("VideoRental.Models.DVD", b =>
                {
                    b.Property<int>("DvdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("GenreKey")
                        .HasColumnType("int");

                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DvdId");

                    b.HasIndex("ActorId");

                    b.HasIndex("CountryId");

                    b.HasIndex("GenreKey");

                    b.ToTable("DVDs");

                    b.HasData(
                        new
                        {
                            DvdId = 1,
                            ActorId = 7,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 1,
                            MovieName = "Men in Black",
                            ReleaseYear = "1997"
                        },
                        new
                        {
                            DvdId = 2,
                            ActorId = 2,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 8,
                            MovieName = "Forrest Gump",
                            ReleaseYear = "1994"
                        },
                        new
                        {
                            DvdId = 3,
                            ActorId = 3,
                            Available = true,
                            CountryId = 4,
                            GenreKey = 4,
                            MovieName = "Harry Potter",
                            ReleaseYear = "2001"
                        },
                        new
                        {
                            DvdId = 4,
                            ActorId = 8,
                            Available = true,
                            CountryId = 3,
                            GenreKey = 3,
                            MovieName = "Leon: The Proffesional",
                            ReleaseYear = "1994"
                        },
                        new
                        {
                            DvdId = 5,
                            ActorId = 12,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 7,
                            MovieName = "Django Unchained",
                            ReleaseYear = "2012"
                        },
                        new
                        {
                            DvdId = 6,
                            ActorId = 11,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 1,
                            MovieName = "Avengers:Endgame",
                            ReleaseYear = "2019"
                        },
                        new
                        {
                            DvdId = 7,
                            ActorId = 1,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 3,
                            MovieName = "Full Metal Jacket",
                            ReleaseYear = "1987"
                        },
                        new
                        {
                            DvdId = 8,
                            ActorId = 12,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 2,
                            MovieName = "The Wolf of Wall Street",
                            ReleaseYear = "2013"
                        },
                        new
                        {
                            DvdId = 9,
                            ActorId = 1,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 3,
                            MovieName = "Pan's Labyrinth",
                            ReleaseYear = "2006"
                        },
                        new
                        {
                            DvdId = 10,
                            ActorId = 1,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 6,
                            MovieName = "The Sixth Sence",
                            ReleaseYear = "1999"
                        },
                        new
                        {
                            DvdId = 11,
                            ActorId = 2,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 3,
                            MovieName = "Catch Me If You Can",
                            ReleaseYear = "2002"
                        },
                        new
                        {
                            DvdId = 12,
                            ActorId = 1,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 2,
                            MovieName = "The Big Lebowski",
                            ReleaseYear = "1998"
                        },
                        new
                        {
                            DvdId = 13,
                            ActorId = 1,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 10,
                            MovieName = "Monsters Inc.",
                            ReleaseYear = "2001"
                        },
                        new
                        {
                            DvdId = 14,
                            ActorId = 1,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 2,
                            MovieName = "Groundhog Day",
                            ReleaseYear = "1993"
                        },
                        new
                        {
                            DvdId = 15,
                            ActorId = 1,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 1,
                            MovieName = "Pirates of the Carribean",
                            ReleaseYear = "2003"
                        },
                        new
                        {
                            DvdId = 16,
                            ActorId = 7,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 9,
                            MovieName = "Aladdin",
                            ReleaseYear = "2019"
                        },
                        new
                        {
                            DvdId = 17,
                            ActorId = 3,
                            Available = true,
                            CountryId = 4,
                            GenreKey = 9,
                            MovieName = "Beauty and the Beast",
                            ReleaseYear = "2017"
                        },
                        new
                        {
                            DvdId = 18,
                            ActorId = 12,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 1,
                            MovieName = "Inception",
                            ReleaseYear = "2010"
                        },
                        new
                        {
                            DvdId = 19,
                            ActorId = 1,
                            Available = true,
                            CountryId = 4,
                            GenreKey = 4,
                            MovieName = "The Lord of the Rings",
                            ReleaseYear = "2002"
                        },
                        new
                        {
                            DvdId = 20,
                            ActorId = 1,
                            Available = true,
                            CountryId = 4,
                            GenreKey = 4,
                            MovieName = "Fantastic Beasts",
                            ReleaseYear = "2019"
                        },
                        new
                        {
                            DvdId = 21,
                            ActorId = 1,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 9,
                            MovieName = "Murder on the Orient Express",
                            ReleaseYear = "2017"
                        },
                        new
                        {
                            DvdId = 22,
                            ActorId = 1,
                            Available = true,
                            CountryId = 4,
                            GenreKey = 9,
                            MovieName = "The Hobbit",
                            ReleaseYear = "2013"
                        },
                        new
                        {
                            DvdId = 23,
                            ActorId = 1,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 9,
                            MovieName = "Alice through the Looking Glass",
                            ReleaseYear = "2016"
                        },
                        new
                        {
                            DvdId = 24,
                            ActorId = 14,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 9,
                            MovieName = "Evan Almighty",
                            ReleaseYear = "2007"
                        },
                        new
                        {
                            DvdId = 25,
                            ActorId = 1,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 9,
                            MovieName = "Deep Sea",
                            ReleaseYear = "2006"
                        },
                        new
                        {
                            DvdId = 26,
                            ActorId = 7,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 5,
                            MovieName = "I am Legend",
                            ReleaseYear = "2007"
                        },
                        new
                        {
                            DvdId = 27,
                            ActorId = 7,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 1,
                            MovieName = "I, Robot",
                            ReleaseYear = "2004"
                        },
                        new
                        {
                            DvdId = 28,
                            ActorId = 6,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 4,
                            MovieName = "Into The Woods",
                            ReleaseYear = "2014"
                        },
                        new
                        {
                            DvdId = 29,
                            ActorId = 1,
                            Available = true,
                            CountryId = 4,
                            GenreKey = 5,
                            MovieName = "Sweeney Todd",
                            ReleaseYear = "2002"
                        },
                        new
                        {
                            DvdId = 30,
                            ActorId = 1,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 9,
                            MovieName = "Finding Neverland",
                            ReleaseYear = "2004"
                        },
                        new
                        {
                            DvdId = 31,
                            ActorId = 1,
                            Available = true,
                            CountryId = 3,
                            GenreKey = 9,
                            MovieName = "The Fifth Element",
                            ReleaseYear = "1997"
                        },
                        new
                        {
                            DvdId = 32,
                            ActorId = 4,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 4,
                            MovieName = "Maleficent",
                            ReleaseYear = "2014"
                        },
                        new
                        {
                            DvdId = 33,
                            ActorId = 4,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 1,
                            MovieName = "Mr. and Mrs. Smith",
                            ReleaseYear = "2005"
                        },
                        new
                        {
                            DvdId = 34,
                            ActorId = 5,
                            Available = true,
                            CountryId = 5,
                            GenreKey = 5,
                            MovieName = "Horns",
                            ReleaseYear = "2013"
                        },
                        new
                        {
                            DvdId = 35,
                            ActorId = 1,
                            Available = true,
                            CountryId = 1,
                            GenreKey = 10,
                            MovieName = "SpongeBob Square Pants",
                            ReleaseYear = "1999"
                        });
                });

            modelBuilder.Entity("VideoRental.Models.Genre", b =>
                {
                    b.Property<int>("GenreKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgeLimit")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreKey");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreKey = 1,
                            AgeLimit = 12,
                            Description = "Some material may not be suitable for children.",
                            GenreName = "Action"
                        },
                        new
                        {
                            GenreKey = 2,
                            AgeLimit = 0,
                            Description = "All ages admitted.",
                            GenreName = "Comedy"
                        },
                        new
                        {
                            GenreKey = 3,
                            AgeLimit = 12,
                            Description = "Some material may not be suitable for children.",
                            GenreName = "Drama"
                        },
                        new
                        {
                            GenreKey = 4,
                            AgeLimit = 0,
                            Description = "All ages admitted.",
                            GenreName = "Fantasy"
                        },
                        new
                        {
                            GenreKey = 5,
                            AgeLimit = 16,
                            Description = "Requires parent accompanying.",
                            GenreName = "Horror"
                        },
                        new
                        {
                            GenreKey = 6,
                            AgeLimit = 12,
                            Description = "Some material may not be suitable for children.",
                            GenreName = "Thriller"
                        },
                        new
                        {
                            GenreKey = 7,
                            AgeLimit = 0,
                            Description = "All ages admitted.",
                            GenreName = "Western"
                        },
                        new
                        {
                            GenreKey = 8,
                            AgeLimit = 12,
                            Description = "Some material may not be suitable for children.",
                            GenreName = "Romantic"
                        },
                        new
                        {
                            GenreKey = 9,
                            AgeLimit = 0,
                            Description = "All ages admitted.",
                            GenreName = "Family"
                        },
                        new
                        {
                            GenreKey = 10,
                            AgeLimit = 0,
                            Description = "All ages admitted.",
                            GenreName = "Cartoon"
                        });
                });

            modelBuilder.Entity("VideoRental.Models.DVD", b =>
                {
                    b.HasOne("VideoRental.Models.Actor", "Actor")
                        .WithMany("DVDs")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoRental.Models.Country", "Country")
                        .WithMany("DVDs")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoRental.Models.Genre", "Genre")
                        .WithMany("DVDs")
                        .HasForeignKey("GenreKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
